# Site settings
title: Imprímela.co
email: imprimela.co@gmail.com
url: https://imprimela.github.io
description: "Innovación y tecnología con
enfoque ambiental."
keywords: "your keywords, separated by commas"
skills: "Impresión 3D - diseño 3D - Impresión fotográfica de alta calidad"
meta_author: Imprimela.co

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: e72e7e #80B3FF
  primary-rgb: "231, 46, 126" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Leonel Andres Alfonso
  location: Bogotá - Colombia 
  social: Red social
  credits: telefonos 

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/imprimela
  - title: facebook
    url:


# Postal address (add as many lines as necessary)
address:
  - line: Carrera 73b 6b 43
  - line: Bogotá - Colombia

# Credits content
credits: '3168126033  -  3504771899'

# Build settings
markdown: kramdown
permalink: pretty
